### PR TITLE
Target .NET Core 3.1

### PR DESCRIPTION
**Pull request by bgrainger**
I'm not sure what your plans for targeting newer versions of .NET Core are, and although I could have opened an issue to discuss first, I was going to do this work anyway, so I thought I'd simply share the code as a PR to start the discussion.

Targetting .NET Core 3.1 will allow newer C# language versions to be used more easily and will use the latest runtime and performance improvements in .NET Core 3.1. It's also an LTS release.

Ported following the instructions at https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30.

### CODE REVIEW

**Comment by OskarKlintrot** [comment]
3.1 has shipped now ;)

Is Newtonsoft really necessary to add now that `System.Text.Json` exists?

**Comment by bgrainger** [comment]
Updated to .NET Core 3.1.

**Comment by praeclarum** [comment]
I'm not sure if I need to change any Azure settings so will wait to the evening to merge.

**Comment by bgrainger** [comment]
Rebased to fix conflicts.

**Comment by bgrainger** [comment]
Rebased (again) to fix conflicts.

**Comment by praeclarum** [comment]
I'll be accepting you .NET 5.0 PR instead. Thanks as always!

**Pull request closed without merging**
