### PR TITLE
Detect extension method and report `this` when found

### PR DESCRIPTION
**Pull request by Therzok**
See individual commits, should be pretty straight forward

### CODE REVIEW

**Comment by TylerBrinkley** [comment]
Is this deployed? If so it's not working for my library at https://www.fuget.org/packages/Enums.NET/2.3.2/lib/netstandard2.0/Enums.NET.dll/EnumsNET/Enums as there should be several extension methods in that class.

Also with this you should be able to close #46.

**Comment by TylerBrinkley** [comment]
I ran this locally and the `this` for extension methods is shown. Looks like there just hasn't been a release yet. Is there any way to add CI/CD to FuGet so that when any changes are merged they're immediately available?

**Comment by praeclarum** [comment]
Strange, the website should be running the master branch. (Azure deploy) Investigating...

**Comment by praeclarum** [comment]
OK, there was a deploy failure:

```
Restore completed in 252.56 ms for D:\home\site\repository\FuGetGallery.csproj.
Data\TypeDocumentation.cs(86,82): error CS1738: Named argument specifications must appear after all fixed arguments have been specified. Please use language version 7.2 or greater to allow non-trailing named arguments. [D:\home\site\repository\FuGetGallery.csproj]
Failed exitCode=1, command=dotnet publish "D:\home\site\repository\FuGetGallery.csproj" --output "D:\local\Temp\8d735576da4e6a8" --configuration Release
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\84.10807.4030\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

Gosh Azure runs ancient versions of software.

**Pull request merged**
