### PR TITLE
Optimize download

### PR DESCRIPTION
**Pull request by praeclarum**
This is a continuation of #139 with fixes for:

- [x] Nuget user agent
- [x] Assembly links

### CODE REVIEW

**Comment by MarkPflug** [comment]
Frank, I had just pushed the fix for the assembly link right before you created this continuation. The issue was that I was using the zip entries *full name* instead of just the filename. Probably should have mentioned I was looking at it.

**Comment by praeclarum** [comment]
@MarkPflug No worries, thanks for letting me know. If it's in your branch, I'll just copy and paste it.

**Comment by MarkPflug** [comment]
Looks like the fix is in this branch, so should be good to go.

**Comment by praeclarum** [comment]
Getting a docs error. 

https://localhost:5001/packages/Microsoft.CodeAnalysis.Common/3.9.0/lib/netstandard2.0/Microsoft.CodeAnalysis.dll/Microsoft.CodeAnalysis.Operations/CommonConversion

```
System.NullReferenceException: Object reference not set to an instance of an object.
         at FuGetGallery.TypeDocumentation..ctor(TypeDefinition typeDefinition, PackageTargetFramework framework, PackageAssemblyXmlDocs xmlDocs, Lazy`1 decompiler, Lazy`1 idecompiler, CSharpFormattingOptions format, String languageCode) in /Users/fak/Dropbox/Projects/FuGetGallery/Data/TypeDocumentation.cs:line 61
         at FuGetGallery.PackageAssembly.GetTypeDocumentation(TypeDefinition typeDefinition, String rawLanguageCode) in /Users/fak/Dropbox/Projects/FuGetGallery/Data/PackageAssembly.cs:line 118
         at FuGetGallery.Pages.packages.Pages_packages_details.ExecuteAsync() in /Users/fak/Dropbox/Projects/FuGetGallery/Pages/packages/details.cshtml:line 64
```

**Pull request merged**
